name: amc
description: A application for AMC

version: 1.0.3+4

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  shared_preferences: ^2.0.13
  fluttertoast: ^8.0.9
  http: ^0.13.4
  flutter_svg: ^1.0.3
  image_picker: ^0.8.5
  flutter_typeahead: 3.2.4
  dio: ^4.0.6
  auto_size_text: ^3.0.0
  flare_flutter: ^3.0.2
  flutter_pdfview: ^1.0.3+3
  flutter_greetings: ^1.0.1
  path_provider: ^2.0.9
  material_design_icons_flutter: ^5.0.6595
  email_validator: ^2.0.1
  badges: ^2.0.2
  webview_flutter: ^3.0.2
  progress_dialog: ^1.2.4
  firebase_messaging: ^11.2.13
  flutter_local_notifications: ^9.4.0
  sqflite: ^2.0.2
  file_utils: ^1.0.1
  percent_indicator: 4.0.0
  url_launcher: ^6.0.20
  shimmer: ^2.0.0
  cached_network_image: ^3.2.0
  flutter_inappwebview: ^5.3.2
  pin_code_fields: ^7.4.0
  flutter_lints: ^1.0.4
  intl: ^0.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animation/
    - assets/html/policy

  fonts:
    - family: Regular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf

    - family: Light
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf

    - family: SemiBold
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf