// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDxAVkr13BgPtoHixCuw53lKV94q1HKKc',
    appId: '1:46169427445:android:4d2c1e6781de50036c24bc',
    messagingSenderId: '46169427445',
    projectId: 'amc-healthcare-services',
    databaseURL: 'https://amc-healthcare-services.firebaseio.com',
    storageBucket: 'amc-healthcare-services.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm2jGK87_UE55_aGWUYivJD3RP2p3Kuk0',
    appId: '1:46169427445:ios:ea64d20825ff3d6e6c24bc',
    messagingSenderId: '46169427445',
    projectId: 'amc-healthcare-services',
    databaseURL: 'https://amc-healthcare-services.firebaseio.com',
    storageBucket: 'amc-healthcare-services.appspot.com',
    iosClientId: '46169427445-jcg4ae54rgsvgqm6qq87l6fv7oighk6f.apps.googleusercontent.com',
    iosBundleId: 'com.instacare.amcapp',
  );
}
